import ReactMarkdown from 'react-markdown'
import { Lightbulb, Zap, Info } from 'lucide-react'
import type { RetentionBrief as RetentionBriefType } from '../types'

interface Props {
  brief: RetentionBriefType
}

export default function RetentionBrief({ brief }: Props) {
  return (
    <div className="card overflow-hidden">
      <div className="px-5 py-4 border-b border-slate-100 flex items-center gap-2">
        <div className="w-7 h-7 rounded-lg bg-teal-50 flex items-center justify-center">
          <Lightbulb size={15} className="text-teal-600" />
        </div>
        <div>
          <h3 className="font-semibold text-slate-900 text-sm">AI Retention Brief</h3>
          <p className="text-xs text-slate-500">Generated by GPT-4o analysis engine</p>
        </div>
      </div>

      {/* Recommended Action callout */}
      <div className="mx-5 mt-5 rounded-xl bg-teal-50 border border-teal-100 px-4 py-3.5 flex items-start gap-3">
        <div className="w-6 h-6 rounded-md bg-teal-100 flex items-center justify-center flex-shrink-0 mt-0.5">
          <Zap size={13} className="text-teal-700" />
        </div>
        <div>
          <p className="text-xs font-semibold text-teal-700 uppercase tracking-wide mb-1">Recommended Action</p>
          <p className="text-sm text-teal-900 font-medium">{brief.recommendedAction}</p>
        </div>
      </div>

      {/* Key Signals */}
      {brief.keySignals.length > 0 && (
        <div className="px-5 mt-4">
          <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Key Signals</p>
          <ul className="space-y-2">
            {brief.keySignals.map((signal, i) => (
              <li key={i} className="flex items-start gap-2.5">
                <span className="w-5 h-5 rounded-full bg-slate-100 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <span className="text-xs font-bold text-slate-500">{i + 1}</span>
                </span>
                <span className="text-sm text-slate-700">{signal}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Brief Markdown */}
      <div className="px-5 mt-5">
        <p className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-3">Full Analysis</p>
        <div className="prose prose-sm prose-slate max-w-none
          prose-headings:font-semibold prose-headings:text-slate-800
          prose-p:text-slate-600 prose-p:leading-relaxed
          prose-strong:text-slate-800 prose-strong:font-semibold
          prose-ul:text-slate-600 prose-li:text-slate-600
          prose-code:text-teal-700 prose-code:bg-teal-50 prose-code:rounded prose-code:px-1">
          <ReactMarkdown>{brief.briefMarkdown}</ReactMarkdown>
        </div>
      </div>

      {/* Confidence note */}
      <div className="mx-5 my-5 rounded-lg bg-slate-50 border border-slate-100 px-4 py-3 flex items-start gap-2.5">
        <Info size={14} className="text-slate-400 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-slate-500 italic">{brief.confidenceNote}</p>
      </div>
    </div>
  )
}
